management:
    endpoints:
        web:
            exposure:
                include: '*'
application:
    security:
        jwt:
            secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
            expiration: 2592000000 # a day
            refresh-token:
                expiration: 604800000 # 7 days

jpa:
    hibernate:
        ddl-auto: create-drop
server:
    port: 8080
spring:
    application:
        name: HIREME-SERVICE
    datasource:
        password: 001002ch
        url: jdbc:mysql://localhost:3306/hiremedb
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 883438160852-f31estk2h47k9jaumf0sogcakptfb1e7.apps.googleusercontent.com
                        client-secret: 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

logging:
    level:
        ROOT: DEBUG

